# Generated by Django 4.2.23 on 2025-10-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectmember_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_view',
            field=models.BooleanField(default=True),
        ),
    ]
