# Generated by Django 4.2.23 on 2025-10-22 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contact'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.contact'),
        ),
    ]
