# Generated by Django 4.2.23 on 2026-03-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_stamp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timersession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
