# Generated by Django 4.2.23 on 2025-10-22 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('Category', 'Category'), ('Client', 'Client')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_address', models.CharField(blank=True, max_length=255)),
                ('company_contact_person', models.CharField(blank=True, max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
    ]
