# Generated by Django 4.2.23 on 2025-10-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_membership_organization_alter_membership_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
