# Generated by Django 4.2.23 on 2025-10-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contact_archived_contact_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
