# Generated by Django 4.2.23 on 2025-11-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='district',
            new_name='county_region',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='street_address',
        ),
    ]
