# Generated by Django 4.2.23 on 2026-03-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_district_userprofile_county_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sv', 'Swedish'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('pt', 'Portuguese')], default='en', max_length=10),
        ),
    ]
