# Generated by Django 4.2.23 on 2026-03-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userincomeconfig',
            name='target_profit_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
