# Generated by Django 4.2.23 on 2026-03-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
