# Generated by Django 4.2.23 on 2025-10-22 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invitation'),
        ('time_entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='duration',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='time_entry_images/'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
